server:
  port: 8090
spring:
  application:
    name: loans
    version: 0.0.1
  datasource:
    url: jdbc:h2:mem:test_db
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO